plugins {
    id 'java'
    id 'jacoco'
    id 'maven-publish'
    id 'com.enonic.xp.base'
    id 'com.enonic.defaults' version '2.1.7'
}

repositories {
    mavenLocal()
    mavenCentral()
    xp.enonicRepo('dev')
}

dependencies {
    implementation libs.guava
    implementation libs.commons.text
    implementation libs.commons.codec
    testImplementation libs.junit.jupiter
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation libs.mockito.core
    testImplementation "com.enonic.xp:testing:${xpVersion}"
    testRuntimeOnly libs.graalvm.js
}

test {
    useJUnitPlatform()
}

def testGraalJs = tasks.register('testGraalJs', Test) {
    group = 'verification'
    description = 'Runs tests with the GraalJS script engine.'
    useJUnitPlatform()
    testClassesDirs = sourceSets.test.output.classesDirs
    classpath = sourceSets.test.runtimeClasspath
    systemProperty 'xp.script-engine', 'GraalJS'
    shouldRunAfter test
}

check.dependsOn testGraalJs

jacocoTestReport {
    reports {
        xml.required = true
        html.required = true
    }
}

check.dependsOn jacocoTestReport

artifacts {
    archives jar
}
